server {

}
    }
        add_header Cache-Control "public, immutable";
        expires 1y;
    location /assets/ {

    }
        try_files $uri $uri/ /index.html;
    location / {

    index index.html;
    root /usr/share/nginx/html;

    server_name localhost;
    listen 80;
